learning_users/basic_app/urls.py
from django.conf.urls import url
from basic_app import views

# Template Tagging
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/$', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

learning_users/learning_users/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'example/', views.example, name='example')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):
    user = models.OneToOneField(User)

    # additional
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

# Import libraries for user login & authentication
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def example(request):
    return HttpResponse("This is an example of how to require login. Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html',
                  {'user_form':user_form,
                   'profile_form':profile_form,
                   'registered':registered})
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active!")
        else:
            print("Someone tried to login and failed!")
            print("Username: {} password {}".format(username, password))
            return("Invalid login details supplied")
    else:
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>HTML Template</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarText">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Django</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
        </li>

        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'basic_app:user_login' %}">Login</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>

  <div class="container">
    {% block body_block %}
      <!-- Anthyhing outside of this will be inherited -->
    {% endblock %}
  </div>
</body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Django Level Five</h1>
  </div>
{% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html'%}
{% block body_block %}

<div class="jumbotron">
  <h1>Please login</h1>

  <form action="{% url 'basic_app:user_login'%}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter Username">

    <label for="password">Password:</label>
    <input type="password" name="password">

    <input type="submit" name="" value="Login">
  </form>
</div>

{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends "basic_app/base.html" %}
{% load staticfiles %}

{% block body_block %}

  <div class="jumbotron">
    {% if registered %}
      <h1>Thank you for registering!</h1>
    {% else %}
      <h1>Register Here!</h1>
      <h3> Fill out the form:</h3>
      <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>
    {% endif %}
  </div>

{% endblock %}